### ISSUE TITLE
Will not launch possible inputs issue

### ISSUE THREAD

**Issue by aradalienzzzz** [skai2/EDAutopilot#13]
c:\EDAutopilot>python autopilot.py
Traceback (most recent call last):
  File "autopilot.py", line 1, in <module>
    from dev_tray import tray
  File "c:\EDAutopilot\dev_tray.py", line 3, in <module>
    from dev_autopilot import autopilot, resource_path, get_bindings, clear_input
  File "c:\EDAutopilot\dev_autopilot.py", line 293, in <module>
    keys = get_bindings(PATH_KEYBINDINGS)
  File "c:\EDAutopilot\dev_autopilot.py", line 280, in get_bindings
    binding['key'] = SCANCODE[binding['pre_key']]
KeyError: 'DIK_'

**Comment by aradalienzzzz** [comment]
c:\EDAutopilot>python autopilot.py
Traceback (most recent call last):
  File "autopilot.py", line 1, in <module>
    from dev_tray import tray
  File "c:\EDAutopilot\dev_tray.py", line 3, in <module>
    from dev_autopilot import autopilot, resource_path, get_bindings, clear_input
  File "c:\EDAutopilot\dev_autopilot.py", line 71
    PATH_LOG_FILES = C:\Users\Aradalien\Saved Games\Frontier Developments\Elite Dangerous

what is the correct log file path as i tried all ? with no luck
