### ISSUE TITLE
syntax error in parse

### ISSUE THREAD

**Issue by SpeedrunnerG55** [skai2/EDAutopilot#34]
```Traceback (most recent call last):
  File "autopilot.py", line 1, in <module>
    from dev_tray import tray
  File "/home/speed/Desktop/EDAutopilot/dev_tray.py", line 3, in <module>
    from dev_autopilot import autopilot, resource_path, get_bindings, clear_input, set_scanner, RELEASE
  File "/home/speed/Desktop/EDAutopilot/dev_autopilot.py", line 382, in <module>
    keys = get_bindings()
  File "/home/speed/Desktop/EDAutopilot/dev_autopilot.py", line 332, in get_bindings
    bindings_tree = parse(latest_bindings)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
```

**Comment by SpeedrunnerG55** [comment]
apparently i was looking in the wrong directory for the bindings and the logs 
```if platform == "linux" or platform == "linux2":
    path_logs = "/home/" + environ['USER'] + "/.steam/steamapps/compatdata/359320/pfx/drive_c/users/steamuser/Saved Games/Frontier Developments/Elite Dangerous"
    path_bindings = "/home/" + environ['USER'] + "/.steam/steamapps/compatdata/359320/pfx/drive_c/users/steamuser/Local Settings/Application Data/Frontier Developments/Elite Dangerous/Options/Bindings"
elif platform == "darwin":
    path_logs = "mac path i dunno"
    path_bindings = "mac path i dunno"
elif platform == "win32":
    path_logs = environ['USERPROFILE'] + "\Saved Games\Frontier Developments\Elite Dangerous"
    path_bindings = environ['LOCALAPPDATA'] + "\Frontier Developments\Elite Dangerous\Options\Bindings"```
fixed it for me
