### ISSUE TITLE
script crash on start

### ISSUE THREAD

**Issue by sofoxe1** [skai2/EDAutopilot#48]
Traceback (most recent call last):
  File "autopilot.py", line 1, in <module>
    from dev_tray import tray
  File "C:\Users\User\Music\EDAutopilot-master\dev_tray.py", line 3, in <module>
    from dev_autopilot import autopilot, resource_path, get_bindings, clear_input, set_scanner, RELEASE
  File "C:\Users\User\Music\EDAutopilot-master\dev_autopilot.py", line 372, in <module>
    keys = get_bindings()
  File "C:\Users\User\Music\EDAutopilot-master\dev_autopilot.py", line 322, in get_bindings
    bindings_tree = parse(latest_bindings)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\xml\etree\ElementTree.py", line 584, in parse
    source = open(source, "rb")
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by Nasa1423** [comment]
Same error

**Comment by kbmorris** [comment]
I believe Python 3.8 is the cause. Change your environment to Python 3.7 and provide feedback.

**Comment by ROLORQ** [comment]
> I believe Python 3.8 is the cause. Change your environment to Python 3.7 and provide feedback.

Hello and thank you! I downgraded my Python installation to 3.7 and it worked!

**Comment by kosssst** [comment]
> I believe Python 3.8 is the cause. Change your environment to Python 3.7 and provide feedback.

@kbmorris I downgraded my Python to 3.7, but this problem is still here
